services:
  - type: web
    name: unep-air-backend
    env: node
    plan: free
    region: oregon
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://unep-air-quality.vercel.app
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: unep_air
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        generateValue: true
    
  - type: pserv
    name: unep-air-db
    env: postgres
    plan: free
    region: oregon
    ipAllowList: []
    databaseName: unep_air
    databaseUser: postgres